//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public string Number { get; set; }
        public System.DateTime RealeseDate { get; set; }
        public int SessionID { get; set; }
        public int PlaceID { get; set; }
        public int StatusID { get; set; }
    
        public virtual Place Place { get; set; }
        public virtual Session Session { get; set; }
        public virtual TicketStatu TicketStatu { get; set; }
    }
}
