//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketPrice
    {
        public int SessionID { get; set; }
        public int SectorID { get; set; }
        public decimal Price { get; set; }
    
        public virtual HallSector HallSector { get; set; }
        public virtual Session Session { get; set; }
    }
}
