//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketHistory
    {
        public int ID { get; set; }
        public string TicketNumber { get; set; }
        public System.DateTime Date { get; set; }
        public int TicketOperationID { get; set; }
        public int WorkerID { get; set; }
    
        public virtual Ticket Ticket { get; set; }
        public virtual TicketOperation TicketOperation { get; set; }
        public virtual User User { get; set; }
    }
}
